In [ ]:
# from tkinter import *
# from PIL import ImageTk, Image

# xpoint = []
# ypoint = []
# if __name__ == "__main__":
#     root = Tk()

#     #setting up a tkinter canvas with scrollbars
#     frame = Frame(root, bd=2, relief=SUNKEN)
#     frame.grid_rowconfigure(0, weight=1)
#     frame.grid_columnconfigure(0, weight=1)
#     xscroll = Scrollbar(frame, orient=HORIZONTAL)
#     xscroll.grid(row=1, column=0, sticky=E+W)
#     yscroll = Scrollbar(frame)
#     yscroll.grid(row=0, column=1, sticky=N+S)
#     canvas = Canvas(frame, bd=0, xscrollcommand=xscroll.set, yscrollcommand=yscroll.set)
#     canvas.grid(row=0, column=0, sticky=N+S+E+W)
#     xscroll.config(command=canvas.xview)
#     yscroll.config(command=canvas.yview)
#     frame.pack(fill=BOTH,expand=1)

#     #adding the image
#     File = "images/images/4.jpg"
# #     File = askopenfilename(parent=root, initialdir="C:/",title='Choose an image.')
#     img = ImageTk.PhotoImage(Image.open(File))
#     canvas.create_image(0,0,image=img,anchor="nw")
#     canvas.config(scrollregion=canvas.bbox(ALL))

#     #function to be called when mouse is clicked
#     def printcoords(event):
#         global xpoint
#         global ypoint
#         #outputting x and y coords to console
#         print (event.x,event.y)
#         xpoint.append(event.x)
#         ypoint.append(event.y)
#     #mouseclick event
#     canvas.bind("<Button 1>",printcoords)

#     root.mainloop()

In [9]:
import cv2 
import numpy as np
import pandas as pd
from sklearn.utils import shuffle
img1 = cv2.imread('images/images/1.jpg') 
img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
img1 = np.array(img1)
img1 = img1.reshape([img1.shape[0] * img1.shape[1]])

img2 = cv2.imread('images/images/2.jpg') 
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
img2 = np.array(img2)
img2 = img2.reshape([img2.shape[0] * img2.shape[1]])

img3 = cv2.imread('images/images/3.jpg') 
img3 = cv2.cvtColor(img3, cv2.COLOR_BGR2GRAY)
img3 = np.array(img3)
img3 = img3.reshape([img3.shape[0] * img3.shape[1]])

img4 = cv2.imread('images/images/4.jpg') 
img4 = cv2.cvtColor(img4, cv2.COLOR_BGR2GRAY)
img4 = np.array(img4)
img4 = img4.reshape([img4.shape[0] * img4.shape[1]])

riv = pd.read_csv('images/images/river.csv')
riv = shuffle(riv)
riv = riv[:50][:]
print(riv.head())
ri = []
for index, row in riv.iterrows():
    ri.append([ img1[(int(row['x'])* 512 )+ int(row['y'])] , img2[(int(row['x'])* 512 )+ int(row['y'])], img3[(int(row['x'])* 512 )+ int(row['y'])], img4[(int(row['x'])* 512 )+ int(row['y'])]])
ri = np.array(ri)
print(ri)
    
nriv = pd.read_csv('images/images/non_river.csv')
nriv = shuffle(nriv)
nriv = nriv[:100][:]
print(nriv.head())
nri = []
for index, row in nriv.iterrows():
    nri.append([ img1[(int(row['x'])* 512 )+ int(row['y'])] , img2[(int(row['x'])* 512 )+ int(row['y'])], img3[(int(row['x'])* 512 )+ int(row['y'])], img4[(int(row['x'])* 512 )+ int(row['y'])]])
nri = np.array(nri)

# print(ri)
mr = ri.sum(axis=0)/ri.shape[0]
mnr = nri.sum(axis=0)/nri.shape[0]
print(nri[10:20])
print(mnr)
print((nri - mnr)[10:20])
covar_r = ((ri - mr).T).dot(ri - mr)
covar_nr = ((nri - mnr).T).dot(nri - mnr)
print(covar_r)
print(covar_nr)


      x    y
14  225  313
27  178  451
25  167  476
18  210  346
3   170  147
[[42 27 30 41]
 [42 27 28 28]
 [40 27 27 38]
 [39 24 27 32]
 [43 28 30 32]
 [43 27 29 33]
 [42 32 37 39]
 [44 29 30 37]
 [43 27 27 31]
 [41 26 27 30]
 [40 25 26 42]
 [46 30 35 42]
 [41 25 27 34]
 [45 31 33 41]
 [51 33 34 39]
 [40 25 25 32]
 [40 24 24 39]
 [38 23 24 24]
 [41 26 27 41]
 [38 24 23 27]
 [44 28 25 35]
 [43 29 36 36]
 [39 23 26 32]
 [41 25 27 33]
 [41 25 26 33]
 [42 26 27 35]
 [38 23 22 25]
 [41 26 26 30]
 [40 26 29 37]
 [42 26 29 30]
 [35 19 19 16]
 [38 23 24 31]
 [47 29 29 41]
 [41 28 28 38]
 [40 25 26 30]
 [54 43 52 41]
 [40 25 27 32]
 [43 27 27 35]
 [45 29 29 33]
 [39 24 24 39]
 [44 31 32 41]
 [42 28 30 33]
 [38 24 24 34]
 [40 25 27 30]
 [40 24 26 31]
 [41 26 26 34]
 [39 23 22 27]
 [38 23 22 35]
 [39 25 24 29]
 [43 29 29 43]]
       x    y
29   275  249
142   72   10
22   265  491
91   221  174
67   122  290
[[39 24 22 30]
 [38 24 23 41]
 [35 20 21 29]
 [40 25 26 36]
 [37 22 21 31]
 [39 25 26 3

In [17]:
test = np.array([img1,img2,img3,img4])
print(test.shape)
rtest = np.zeros(test.shape)
for i in range(test.shape[1]):
    rtest[0][i] = test[0][i] - mr[0]
    rtest[1][i] = test[1][i] - mr[1]
    rtest[2][i] = test[2][i] - mr[2]
    rtest[3][i] = test[3][i] - mr[3]

nrtest = np.zeros(test.shape)
for i in range(test.shape[1]):
    nrtest[0][i] = test[0][i] - mnr[0]
    nrtest[1][i] = test[1][i] - mnr[1]
    nrtest[2][i] = test[2][i] - mnr[2]
    nrtest[3][i] = test[3][i] - mnr[3]
#     print(nrtest[0][i])
print(rtest)
print(nrtest)

(4, 262144)
[[ -0.52  -2.52  -2.52 ...  -4.52  -4.52  -3.52]
 [  0.46   0.46  -0.54 ...  -4.54  -4.54  -4.54]
 [  0.2    0.2   -1.8  ...  -7.8   -7.8   -7.8 ]
 [  6.98   7.98   6.98 ...  -7.02  -2.02 -13.02]]
[[  0.64  -1.36  -1.36 ...  -3.36  -3.36  -2.36]
 [  1.26   1.26   0.26 ...  -3.74  -3.74  -3.74]
 [  1.69   1.69  -0.31 ...  -6.31  -6.31  -6.31]
 [  6.69   7.69   6.69 ...  -7.31  -2.31 -13.31]]


In [26]:
gg = ((nrtest.T).dot(np.linalg.inv(covar_r)))
gg.dot(nrtest)
# r_class = ((nrtest.T).dot(np.linalg.inv(covar_r))).dot(nrtest)

MemoryError: 